#include:
 # - template: Auto-DevOps.gitlab-ci.yml

#variables:
#  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
#  TEST_DISABLED: "true"
#  DAST_DISABLED: "true"

image: gregwolford/veracode_node:latest
#
stages:
  - Build
  - Archive
  - Veracode_Software_Composition_analysis
  - Veracode_static_analysis
  - Veracode_PipelineScan
  - deploy

build-image:
  stage: Build
  script:
      # - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/22.1.9.3/vosp-api-wrappers-java-22.1.9.3.jar
      #- curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      #- unzip pipeline-scan-LATEST.zip pipeline-scan.jar
      - ls
      #- apt-get update -y
      #- apt-get -y install default-jdk
    
package-zip:
    stage: Archive
    script:
        - git archive -o VeracodePackage.zip HEAD     
    artifacts:
        paths:
            - VeracodePackage.zip

Veracode_software_composition_analysis:
    stage: Veracode_Software_Composition_analysis
    script:
        - export JAVA_OPTS="-Xms1G -Xmx3G"
        - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan . --allow-dirty --update-advisor
    allow_failure: true



Veracode_static_analysis:
    stage: Veracode_static_analysis
    before_script:
                #- wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/20.8.7.1/vosp-api-wrappers-java-20.8.7.1.jar
    script:
        #- apt-get update -y
        #- apt-get -y install default-jdk
        - java -jar veracode/veracode-wrapper.jar -vid ${V_ID} -vkey ${V_KEY}
          -action UploadAndScan -appname "JuiceShop - Gitlab" -createprofile true -autoscan true -filepath VeracodePackage.zip -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"

Veracode_PipelineScan:
    stage: Veracode_PipelineScan
    artifacts:
        name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_pipeline-results
        paths:
            - results.json
        expire_in: 1 week
    when: always
    script:
        - pwd
        - ls
        #- apt-get update -y
        #- apt-get -y install default-jdk
        #- curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        #- unzip pipeline-scan-LATEST.zip pipeline-scan.jar
        - java -jar veracode/pipeline-scan.jar
            --veracode_api_id "${V_ID}"
            --veracode_api_key "${V_KEY}"
            --file "VeracodePackage.zip"
            --fail_on_severity="Very High, High"
            --fail_on_cwe="80"
            --json_output_file="baseline.json"
            --project_name "${CI_PROJECT_PATH}"
            --project_url "${CI_REPOSITORY_URL}"
            --project_ref "${CI_COMMIT_REF_NAME}"           
            --timeout "${CI_TIMEOUT}"            
            --issue_details true
            --gl_issue_generation true
    allow_failure: true


deploy:
  stage: deploy
  script:
    - echo deploy!
